pipeline {
    agent any
    stages {
         stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'cred', url: "Git repo URL"
            }
        }

        stage('Build the docker images') {
            steps {
                sh "cd '${WORKSPACE}/webelight_practical_test' && docker build -t testapplication ."
            } 
        }

        stage('Push the image to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                    sh 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
                    sh 'docker push <username>/testapplication:latest'
                }
            }
        }

    }
}